import { Router } from 'express';
import healthRouter from './health.routes';
import adminAuthRouter from './adminAuth.routes';
import adminCategoryRouter from './adminCategory.routes';
import adminLocationRouter from './adminLocation.routes';
import adminCareerAdviceRouter from './adminCareerAdvice.routes';
import adminReportRouter from './adminReport.routes';
import adminSubscriptionPlanRouter from './adminSubscriptionPlan.routes';
import adminSubscriptionRouter from './adminSubscription.routes';
import { adminCityPackageRouter, employerCityPackageRouter } from './cityPackage.routes';
import adminCouponRouter from './adminCoupon.routes';
import adminAnalyticsRouter from './adminAnalytics.routes';
import adminUserRouter from './adminUser.routes';
import adminCandidateRouter from './adminCandidate.routes';
import adminEmployerRouter from './adminEmployer.routes';
import adminCompanyRouter from './adminCompany.routes';
import adminJobRouter from './adminJob.routes';
import adminApplicationRouter from './adminApplication.routes';
import adminInterviewRouter from './adminInterview.routes';
import adminAuditRouter from './adminAudit.routes';
import adminSettingsRouter from './adminSettings.routes';
import adminAiFeatureRouter from './adminAiFeature.routes';
import adminTaxonomyRouter from './adminTaxonomy.routes';
import adminBannerRouter from './adminBanner.routes';
import adminRoleAdRouter from './adminRoleAd.routes';
import adminReferralRouter from './adminReferral.routes';
import adminFaqRouter from './adminFaq.routes';
import adminNotificationRouter from './adminNotification.routes';
import adminSupportTicketRouter from './adminSupportTicket.routes';
import adminChatRouter from './adminChat.routes';
import adminSystemRouter from './adminSystem.routes';
import candidateAuthRouter from './candidateAuth.routes';
import candidateProfileRouter from './candidateProfile.routes';
import savedJobRouter from './savedJob.routes';
import candidateApplyRouter from './candidateApply.routes';
import candidateApplicationRouter from './candidateApplication.routes';
import candidateInvitationRouter from './candidateInvitation.routes';
import candidateInterviewRouter from './candidateInterview.routes';
import candidateSavedSearchRouter from './candidateSavedSearch.routes';
import candidateAiRouter from './candidateAi.routes';
import candidateRoleAdRouter from './candidateRoleAd.routes';
import candidateReferralRouter from './candidateReferral.routes';
import { candidateChatRouter, employerChatRouter } from './chat.routes';
import employerAuthRouter from './employerAuth.routes';
import employerReferralRouter from './employerReferral.routes';
import employerTeamRouter from './employerTeam.routes';
import employerProfileRouter from './employerProfile.routes';
import employerJobRouter from './employerJob.routes';
import employerApplicationRouter from './employerApplication.routes';
import employerInvitationRouter from './employerInvitation.routes';
import employerCandidateRouter from './employerCandidate.routes';
import employerInterviewRouter from './employerInterview.routes';
import employerSubscriptionRouter from './employerSubscription.routes';
import employerPaymentRouter from './employerPayment.routes';
import paymentGatewayRouter from './paymentGateway.routes';
import employerAnalyticsRouter from './employerAnalytics.routes';
import employerAiRouter from './employerAi.routes';
import candidateSafetyRouter from './candidateSafety.routes';
import companyRouter from './company.routes';
import categoryRouter from './category.routes';
import locationRouter from './location.routes';
import placesRouter from './places.routes';
import jobRouter from './job.routes';
import notificationRouter from './notification.routes';
import careerAdviceRouter from './careerAdvice.routes';
import reportRouter from './report.routes';
import supportTicketRouter from './supportTicket.routes';
import subscriptionPlanRouter from './subscriptionPlan.routes';
import mediaPublicRouter from './media.routes';
import settingsPublicRouter from './settings.routes';
import bannerPublicRouter from './banner.routes';
import faqPublicRouter from './faq.routes';
import adminPaymentRouter from './adminPayment.routes';
import { maintenanceGate } from '../middlewares/maintenance.middleware';

/**
 * API v1 route aggregator.
 */
const v1Router = Router();

v1Router.use(maintenanceGate);

v1Router.use('/health', healthRouter);
v1Router.use('/media', mediaPublicRouter);
v1Router.use('/settings', settingsPublicRouter);
v1Router.use('/banners', bannerPublicRouter);
v1Router.use('/faqs', faqPublicRouter);
v1Router.use('/admin/auth', adminAuthRouter);
v1Router.use('/admin/settings', adminSettingsRouter);
v1Router.use('/admin/ai-features', adminAiFeatureRouter);
v1Router.use('/admin/categories', adminCategoryRouter);
v1Router.use('/admin/locations', adminLocationRouter);
v1Router.use('/admin/career-advice', adminCareerAdviceRouter);
v1Router.use('/admin/reports', adminReportRouter);
v1Router.use('/admin/subscription-plans', adminSubscriptionPlanRouter);
v1Router.use('/admin/subscriptions', adminSubscriptionRouter);
v1Router.use('/admin/city-packages', adminCityPackageRouter);
v1Router.use('/employer/city-packages', employerCityPackageRouter);
v1Router.use('/admin/payments', adminPaymentRouter);
v1Router.use('/admin/coupons', adminCouponRouter);
v1Router.use('/admin/analytics', adminAnalyticsRouter);
v1Router.use('/admin/admin-users', adminUserRouter);
v1Router.use('/admin/candidates', adminCandidateRouter);
v1Router.use('/admin/employers', adminEmployerRouter);
v1Router.use('/admin/companies', adminCompanyRouter);
v1Router.use('/admin/jobs', adminJobRouter);
v1Router.use('/admin/applications', adminApplicationRouter);
v1Router.use('/admin/interviews', adminInterviewRouter);
v1Router.use('/admin/audit-logs', adminAuditRouter);
v1Router.use('/admin/taxonomies', adminTaxonomyRouter);
v1Router.use('/admin/banners', adminBannerRouter);
v1Router.use('/admin/role-ads', adminRoleAdRouter);
v1Router.use('/admin/referrals', adminReferralRouter);
v1Router.use('/admin/faqs', adminFaqRouter);
v1Router.use('/admin/notifications', adminNotificationRouter);
v1Router.use('/admin/support/tickets', adminSupportTicketRouter);
v1Router.use('/admin/chat', adminChatRouter);
v1Router.use('/admin/system', adminSystemRouter);
v1Router.use('/candidate/auth', candidateAuthRouter);
v1Router.use('/candidate/profile', candidateProfileRouter);
v1Router.use('/candidate/safety', candidateSafetyRouter);
v1Router.use('/candidate/saved-jobs', savedJobRouter);
v1Router.use('/candidate/saved-searches', candidateSavedSearchRouter);
v1Router.use('/candidate/ai', candidateAiRouter);
v1Router.use('/candidate/role-ads', candidateRoleAdRouter);
v1Router.use('/candidate/referrals', candidateReferralRouter);
v1Router.use('/candidate/chat', candidateChatRouter);
v1Router.use('/candidate/jobs', candidateApplyRouter);
v1Router.use('/candidate/applications', candidateApplicationRouter);
v1Router.use('/candidate/invitations', candidateInvitationRouter);
v1Router.use('/candidate/interviews', candidateInterviewRouter);
v1Router.use('/employer/auth', employerAuthRouter);
v1Router.use('/employer/referrals', employerReferralRouter);
v1Router.use('/employer/team', employerTeamRouter);
v1Router.use('/employer/chat', employerChatRouter);
v1Router.use('/employer/jobs', employerJobRouter);
v1Router.use('/employer/applications', employerApplicationRouter);
v1Router.use('/employer/invitations', employerInvitationRouter);
v1Router.use('/employer/candidates', employerCandidateRouter);
v1Router.use('/employer/interviews', employerInterviewRouter);
v1Router.use('/employer/ai', employerAiRouter);
v1Router.use('/employer', employerSubscriptionRouter);
v1Router.use('/employer', employerPaymentRouter);
v1Router.use('/employer', employerAnalyticsRouter);
v1Router.use('/employer', employerProfileRouter);
v1Router.use('/companies', companyRouter);
v1Router.use('/categories', categoryRouter);
v1Router.use('/locations', locationRouter);
v1Router.use('/places', placesRouter);
v1Router.use('/jobs', jobRouter);
v1Router.use('/notifications', notificationRouter);
v1Router.use('/career-advice', careerAdviceRouter);
v1Router.use('/reports', reportRouter);
v1Router.use('/support/tickets', supportTicketRouter);
v1Router.use('/payments', paymentGatewayRouter);
v1Router.use('/subscription-plans', subscriptionPlanRouter);

export default v1Router;
