import { HTTP_STATUS } from '../constants';
import { Candidate } from '../models/Candidate';
import { Company } from '../models/Company';
import { Job } from '../models/Job';
import { User } from '../models/User';
import type { AuthenticatedCandidate } from '../types/auth.types';
import { AppError } from '../utils/AppError';
import { buildPublicVisibilityFilter } from '../utils/jobSearchQuery';
import { scoreJobMatch } from '../utils/matchScore';
import { normalizeRoleKey } from '../utils/roleAdMatch';
import { openAiService } from './openai.service';
import { roleAdService } from './roleAd.service';

async function loadPublicJobsFilter(now = new Date()) {
  const companies = await Company.find({
    status: 'active',
    verificationStatus: { $ne: 'rejected' },
  })
    .select('_id')
    .lean();
  const companyIds = companies.map((c) => c._id);
  if (companyIds.length === 0) return null;
  return buildPublicVisibilityFilter(companyIds, now);
}

export const AI_COACH_LABEL = 'AI-generated';
export const AI_COACH_DISCLAIMER =
  'This career coaching was generated by AI (ChatGPT). It is guidance only — not financial, legal, or hiring advice. Review before acting.';

export class AiCareerCoachService {
  /**
   * 109–112: Career coach pack — recommendations, salary guidance, missing skills.
   */
  async getCoach(candidate: AuthenticatedCandidate) {
    const [user, candidateDoc] = await Promise.all([
      User.findById(candidate.userId).select('name email phone'),
      Candidate.findById(candidate.candidateId),
    ]);
    if (!user || !candidateDoc) {
      throw new AppError('Candidate not found', HTTP_STATUS.NOT_FOUND);
    }

    const visibility = await loadPublicJobsFilter();
    const jobs = visibility
      ? await Job.find(visibility)
          .sort({ featured: -1, publishedAt: -1 })
          .limit(40)
          .select(
            'title skills requirements experienceMin experienceMax salaryMin salaryMax workMode location',
          )
          .lean()
      : [];

    const candidateSource = {
      headline: candidateDoc.headline,
      currentJobTitle: candidateDoc.currentJobTitle,
      skills: candidateDoc.skills,
      totalExperience: candidateDoc.totalExperience,
      expectedSalary: candidateDoc.expectedSalary,
      currentLocation: candidateDoc.currentLocation,
      latitude: candidateDoc.latitude,
      longitude: candidateDoc.longitude,
      openToWork: candidateDoc.openToWork,
      availableFrom: candidateDoc.availableFrom,
      noticePeriod: candidateDoc.noticePeriod,
    };

    const topJobs = jobs
      .map((job) => ({
        title: job.title,
        skills: job.skills ?? [],
        salaryMin: job.salaryMin ?? null,
        salaryMax: job.salaryMax ?? null,
        workMode: job.workMode,
        location: job.location?.displayName || job.location?.city || '',
        match: scoreJobMatch(
          {
            title: job.title,
            skills: job.skills,
            requirements: job.requirements,
            experienceMin: job.experienceMin,
            experienceMax: job.experienceMax,
            salaryMin: job.salaryMin,
            salaryMax: job.salaryMax,
            workMode: job.workMode,
            locationText: job.location?.displayName || job.location?.city || '',
            latitude: job.location?.latitude,
            longitude: job.location?.longitude,
          },
          candidateSource,
        ),
      }))
      .sort((a, b) => b.match.overall - a.match.overall)
      .slice(0, 10);

    const missingSkillCounts = new Map<string, number>();
    for (const row of topJobs) {
      for (const skill of row.match.missingSkills) {
        const key = skill.toLowerCase();
        missingSkillCounts.set(key, (missingSkillCounts.get(key) ?? 0) + 1);
      }
    }
    const hotMissingSkills = [...missingSkillCounts.entries()]
      .sort((a, b) => b[1] - a[1])
      .slice(0, 12)
      .map(([skill, count]) => ({ skill, demandCount: count }));

    const profile = {
      name: user.name ?? '',
      headline: candidateDoc.headline ?? '',
      currentJobTitle: candidateDoc.currentJobTitle ?? '',
      currentCompany: candidateDoc.currentCompany ?? '',
      skills: candidateDoc.skills ?? [],
      totalExperience: candidateDoc.totalExperience ?? 0,
      expectedSalary: candidateDoc.expectedSalary ?? null,
      currentSalary: candidateDoc.currentSalary ?? null,
      currentLocation: candidateDoc.currentLocation ?? '',
      preferredRoles: candidateDoc.preferredRoles ?? [],
      preferredLocations: candidateDoc.preferredLocations ?? [],
      openToWork: candidateDoc.openToWork ?? true,
    };

    let coach: Record<string, unknown>;
    let model = 'profile';
    let usedAi = false;
    try {
      const result = await openAiService.chatJson(
        [
          {
            role: 'system',
            content: `You are an AI Career Coach for WorkIndia (Indian job market).
Return JSON only:
{
  "coachSummary": "2-3 sentences",
  "careerRecommendations": [{"title":"...","why":"...","priority":"high|medium|low"}],
  "jobRecommendations": [{"title":"...","why":"...","targetMatchHint":"..."}],
  "salaryGuidance": {
    "suggestedMin": number|null,
    "suggestedMax": number|null,
    "currency": "INR",
    "period": "yearly",
    "rationale": "...",
    "negotiationTips": ["..."]
  },
  "missingSkillSuggestions": [{"skill":"...","why":"...","howToLearn":"..."}],
  "actionPlan": ["..."]
}
Rules:
- Base advice on the profile + market snapshot only.
- Do not invent employers the candidate worked at.
- Salary numbers must be INR yearly estimates when possible.
- Always write as coaching guidance, AI-assisted.`,
          },
          {
            role: 'user',
            content: JSON.stringify({
              profile,
              marketSnapshot: {
                topMatchedJobs: topJobs.map((j) => ({
                  title: j.title,
                  matchPercentage: j.match.overall,
                  matchingSkills: j.match.matchingSkills,
                  missingSkills: j.match.missingSkills,
                  salaryMin: j.salaryMin,
                  salaryMax: j.salaryMax,
                })),
                hotMissingSkills,
              },
            }),
          },
        ],
        { temperature: 0.45 },
      );
      model = result.model;
      coach = JSON.parse(result.content) as Record<string, unknown>;
      usedAi = true;
    } catch {
      const roleLabel = profile.currentJobTitle || profile.headline || 'your current role';
      const suggestions = hotMissingSkills.slice(0, 8).map((item) => ({
        skill: item.skill,
        why: `Jobs close to ${roleLabel} often ask for ${item.skill}, and it is not on your profile yet.`,
        howToLearn: `Take a short ${item.skill} course, then add it to your skills.`,
      }));
      const jobHighs = topJobs
        .map((job) => job.salaryMax)
        .filter((value): value is number => typeof value === 'number' && value > 0);
      coach = {
        coachSummary: suggestions.length
          ? `As someone in ${roleLabel}, these skills show up on jobs that fit you and are still missing from your profile.`
          : `Your profile already covers the skills on the closest open jobs.`,
        careerRecommendations: topJobs.slice(0, 4).map((job) => ({
          title: job.title,
          why: `${job.match.overall}% match with your current profile.`,
        })),
        jobRecommendations: topJobs.slice(0, 4).map((job) => ({
          title: job.title,
          why: job.match.missingSkills.length
            ? `Still missing: ${job.match.missingSkills.slice(0, 3).join(', ')}.`
            : 'Strong overlap with your skills.',
        })),
        salaryGuidance: {
          suggestedMin: profile.expectedSalary,
          suggestedMax: jobHighs.length ? Math.max(...jobHighs) : profile.expectedSalary,
          currency: 'INR',
          period: 'yearly',
          rationale: 'Based on your expected salary and the closest matching jobs.',
          negotiationTips: [],
        },
        missingSkillSuggestions: suggestions,
        actionPlan: suggestions.slice(0, 4).map((item) => `Learn ${item.skill} and add it to your profile.`),
      };
    }

    const salaryGuidance = (coach.salaryGuidance ?? {}) as Record<string, unknown>;
    const missingSkillSuggestions = Array.isArray(coach.missingSkillSuggestions)
      ? coach.missingSkillSuggestions.slice(0, 10)
      : [];
    const skillNames = [
      profile.currentJobTitle,
      profile.headline,
      ...(Array.isArray(profile.preferredRoles) ? profile.preferredRoles : []),
      ...topJobs.map((job) => job.title),
      ...missingSkillSuggestions
        .map((item) =>
          item && typeof item === 'object' && typeof (item as { skill?: unknown }).skill === 'string'
            ? (item as { skill: string }).skill
            : '',
        )
        .filter(Boolean),
      ...hotMissingSkills.map((item) => item.skill),
    ];
    let sponsoredAds: Awaited<ReturnType<typeof roleAdService.findLiveForSkills>> = [];
    try {
      sponsoredAds = await roleAdService.findLiveForSkills(skillNames);
    } catch {
      sponsoredAds = [];
    }
    const missingWithAds = missingSkillSuggestions.map((item) => {
      const skill =
        item && typeof item === 'object' && typeof (item as { skill?: unknown }).skill === 'string'
          ? (item as { skill: string }).skill
          : '';
      const skillKey = normalizeRoleKey(skill);
      const ads = sponsoredAds.filter((ad) =>
        ad.matchedSkills.some((matched) => normalizeRoleKey(matched) === skillKey),
      );
      return item && typeof item === 'object' ? { ...(item as Record<string, unknown>), ads } : item;
    });

    return {
      aiGenerated: usedAi,
      aiLabel: usedAi ? AI_COACH_LABEL : 'Profile match',
      aiDisclaimer: usedAi
        ? AI_COACH_DISCLAIMER
        : 'Guidance is based on your profile and open jobs. Review it before you act.',
      provider: usedAi ? ('openai' as const) : ('rules' as const),
      model,
      generatedAt: new Date().toISOString(),
      purpose: 'career_coach' as const,
      uiHint: {
        showAiBadge: usedAi,
        badgeText: usedAi ? 'AI-generated' : 'Profile match',
        bannerText: usedAi
          ? 'AI Career Coach — guidance only, review carefully'
          : 'Skill gaps from jobs that match your profile',
      },
      coachSummary: typeof coach.coachSummary === 'string' ? coach.coachSummary.trim() : '',
      careerRecommendations: Array.isArray(coach.careerRecommendations)
        ? coach.careerRecommendations.slice(0, 8)
        : [],
      jobRecommendations: Array.isArray(coach.jobRecommendations)
        ? coach.jobRecommendations.slice(0, 8)
        : [],
      salaryGuidance: {
        suggestedMin:
          typeof salaryGuidance.suggestedMin === 'number' ? salaryGuidance.suggestedMin : null,
        suggestedMax:
          typeof salaryGuidance.suggestedMax === 'number' ? salaryGuidance.suggestedMax : null,
        currency: typeof salaryGuidance.currency === 'string' ? salaryGuidance.currency : 'INR',
        period: typeof salaryGuidance.period === 'string' ? salaryGuidance.period : 'yearly',
        rationale: typeof salaryGuidance.rationale === 'string' ? salaryGuidance.rationale : '',
        negotiationTips: Array.isArray(salaryGuidance.negotiationTips)
          ? salaryGuidance.negotiationTips.filter((x): x is string => typeof x === 'string').slice(0, 6)
          : [],
      },
      missingSkillSuggestions: missingWithAds,
      sponsoredAds,
      actionPlan: Array.isArray(coach.actionPlan)
        ? coach.actionPlan.filter((x): x is string => typeof x === 'string').slice(0, 8)
        : [],
      marketHints: {
        hotMissingSkills,
        topMatchTitles: topJobs.slice(0, 5).map((j) => j.title),
      },
    };
  }
}

export const aiCareerCoachService = new AiCareerCoachService();
