import { HTTP_STATUS } from '../constants';
import { Candidate } from '../models/Candidate';
import { Company } from '../models/Company';
import { Job } from '../models/Job';
import { User } from '../models/User';
import type { AuthenticatedCandidate } from '../types/auth.types';
import { AppError } from '../utils/AppError';
import { buildPublicVisibilityFilter } from '../utils/jobSearchQuery';
import { scoreJobMatch } from '../utils/matchScore';
import { openAiService } from './openai.service';

async function loadPublicJobsFilter(now = new Date()) {
  const companies = await Company.find({
    status: 'active',
    verificationStatus: { $ne: 'rejected' },
  })
    .select('_id')
    .lean();
  const companyIds = companies.map((c) => c._id);
  if (companyIds.length === 0) return null;
  return buildPublicVisibilityFilter(companyIds, now);
}

export const AI_COACH_LABEL = 'AI-generated';
export const AI_COACH_DISCLAIMER =
  'This career coaching was generated by AI (ChatGPT). It is guidance only — not financial, legal, or hiring advice. Review before acting.';

export class AiCareerCoachService {
  /**
   * 109–112: Career coach pack — recommendations, salary guidance, missing skills.
   */
  async getCoach(candidate: AuthenticatedCandidate) {
    const [user, candidateDoc] = await Promise.all([
      User.findById(candidate.userId).select('name email phone'),
      Candidate.findById(candidate.candidateId),
    ]);
    if (!user || !candidateDoc) {
      throw new AppError('Candidate not found', HTTP_STATUS.NOT_FOUND);
    }

    const visibility = await loadPublicJobsFilter();
    const jobs = visibility
      ? await Job.find(visibility)
          .sort({ featured: -1, publishedAt: -1 })
          .limit(40)
          .select(
            'title skills requirements experienceMin experienceMax salaryMin salaryMax workMode location',
          )
          .lean()
      : [];

    const candidateSource = {
      headline: candidateDoc.headline,
      currentJobTitle: candidateDoc.currentJobTitle,
      skills: candidateDoc.skills,
      totalExperience: candidateDoc.totalExperience,
      expectedSalary: candidateDoc.expectedSalary,
      currentLocation: candidateDoc.currentLocation,
      latitude: candidateDoc.latitude,
      longitude: candidateDoc.longitude,
      openToWork: candidateDoc.openToWork,
      availableFrom: candidateDoc.availableFrom,
      noticePeriod: candidateDoc.noticePeriod,
    };

    const topJobs = jobs
      .map((job) => ({
        title: job.title,
        skills: job.skills ?? [],
        salaryMin: job.salaryMin ?? null,
        salaryMax: job.salaryMax ?? null,
        workMode: job.workMode,
        location: job.location?.displayName || job.location?.city || '',
        match: scoreJobMatch(
          {
            title: job.title,
            skills: job.skills,
            requirements: job.requirements,
            experienceMin: job.experienceMin,
            experienceMax: job.experienceMax,
            salaryMin: job.salaryMin,
            salaryMax: job.salaryMax,
            workMode: job.workMode,
            locationText: job.location?.displayName || job.location?.city || '',
            latitude: job.location?.latitude,
            longitude: job.location?.longitude,
          },
          candidateSource,
        ),
      }))
      .sort((a, b) => b.match.overall - a.match.overall)
      .slice(0, 10);

    const missingSkillCounts = new Map<string, number>();
    for (const row of topJobs) {
      for (const skill of row.match.missingSkills) {
        const key = skill.toLowerCase();
        missingSkillCounts.set(key, (missingSkillCounts.get(key) ?? 0) + 1);
      }
    }
    const hotMissingSkills = [...missingSkillCounts.entries()]
      .sort((a, b) => b[1] - a[1])
      .slice(0, 12)
      .map(([skill, count]) => ({ skill, demandCount: count }));

    const profile = {
      name: user.name ?? '',
      headline: candidateDoc.headline ?? '',
      currentJobTitle: candidateDoc.currentJobTitle ?? '',
      currentCompany: candidateDoc.currentCompany ?? '',
      skills: candidateDoc.skills ?? [],
      totalExperience: candidateDoc.totalExperience ?? 0,
      expectedSalary: candidateDoc.expectedSalary ?? null,
      currentSalary: candidateDoc.currentSalary ?? null,
      currentLocation: candidateDoc.currentLocation ?? '',
      preferredRoles: candidateDoc.preferredRoles ?? [],
      preferredLocations: candidateDoc.preferredLocations ?? [],
      openToWork: candidateDoc.openToWork ?? true,
    };

    const { content, model } = await openAiService.chatJson(
      [
        {
          role: 'system',
          content: `You are an AI Career Coach for WorkIndia (Indian job market).
Return JSON only:
{
  "coachSummary": "2-3 sentences",
  "careerRecommendations": [{"title":"...","why":"...","priority":"high|medium|low"}],
  "jobRecommendations": [{"title":"...","why":"...","targetMatchHint":"..."}],
  "salaryGuidance": {
    "suggestedMin": number|null,
    "suggestedMax": number|null,
    "currency": "INR",
    "period": "yearly",
    "rationale": "...",
    "negotiationTips": ["..."]
  },
  "missingSkillSuggestions": [{"skill":"...","why":"...","howToLearn":"..."}],
  "actionPlan": ["..."]
}
Rules:
- Base advice on the profile + market snapshot only.
- Do not invent employers the candidate worked at.
- Salary numbers must be INR yearly estimates when possible.
- Always write as coaching guidance, AI-assisted.`,
        },
        {
          role: 'user',
          content: JSON.stringify({
            profile,
            marketSnapshot: {
              topMatchedJobs: topJobs.map((j) => ({
                title: j.title,
                matchPercentage: j.match.overall,
                matchingSkills: j.match.matchingSkills,
                missingSkills: j.match.missingSkills,
                salaryMin: j.salaryMin,
                salaryMax: j.salaryMax,
              })),
              hotMissingSkills,
            },
          }),
        },
      ],
      { temperature: 0.45 },
    );

    let coach: Record<string, unknown>;
    try {
      coach = JSON.parse(content) as Record<string, unknown>;
    } catch {
      throw new AppError('AI career coach returned invalid JSON', HTTP_STATUS.SERVICE_UNAVAILABLE);
    }

    const salaryGuidance = (coach.salaryGuidance ?? {}) as Record<string, unknown>;

    return {
      aiGenerated: true as const,
      aiLabel: AI_COACH_LABEL,
      aiDisclaimer: AI_COACH_DISCLAIMER,
      provider: 'openai' as const,
      model,
      generatedAt: new Date().toISOString(),
      purpose: 'career_coach' as const,
      uiHint: {
        showAiBadge: true as const,
        badgeText: 'AI-generated',
        bannerText: 'AI Career Coach — guidance only, review carefully',
      },
      coachSummary: typeof coach.coachSummary === 'string' ? coach.coachSummary.trim() : '',
      careerRecommendations: Array.isArray(coach.careerRecommendations)
        ? coach.careerRecommendations.slice(0, 8)
        : [],
      jobRecommendations: Array.isArray(coach.jobRecommendations)
        ? coach.jobRecommendations.slice(0, 8)
        : [],
      salaryGuidance: {
        suggestedMin:
          typeof salaryGuidance.suggestedMin === 'number' ? salaryGuidance.suggestedMin : null,
        suggestedMax:
          typeof salaryGuidance.suggestedMax === 'number' ? salaryGuidance.suggestedMax : null,
        currency: typeof salaryGuidance.currency === 'string' ? salaryGuidance.currency : 'INR',
        period: typeof salaryGuidance.period === 'string' ? salaryGuidance.period : 'yearly',
        rationale: typeof salaryGuidance.rationale === 'string' ? salaryGuidance.rationale : '',
        negotiationTips: Array.isArray(salaryGuidance.negotiationTips)
          ? salaryGuidance.negotiationTips.filter((x): x is string => typeof x === 'string').slice(0, 6)
          : [],
      },
      missingSkillSuggestions: Array.isArray(coach.missingSkillSuggestions)
        ? coach.missingSkillSuggestions.slice(0, 10)
        : [],
      actionPlan: Array.isArray(coach.actionPlan)
        ? coach.actionPlan.filter((x): x is string => typeof x === 'string').slice(0, 8)
        : [],
      marketHints: {
        hotMissingSkills,
        topMatchTitles: topJobs.slice(0, 5).map((j) => j.title),
      },
    };
  }
}

export const aiCareerCoachService = new AiCareerCoachService();
