import { HTTP_STATUS } from '../constants';
import { Candidate } from '../models/Candidate';
import { Company } from '../models/Company';
import { Job } from '../models/Job';
import { User } from '../models/User';
import type { AuthenticatedCandidate } from '../types/auth.types';
import { AppError } from '../utils/AppError';
import { openAiService } from './openai.service';
import type {
  AiResumeBuildInput,
  AiResumeTailorInput,
} from '../validators/aiResume.validator';

/** Shared AI provenance fields — always present so clients can label UI clearly. */
export const AI_RESUME_LABEL = 'AI-generated';
export const AI_RESUME_DISCLAIMER =
  'This content was generated by AI (ChatGPT). Review and edit before using, uploading, or sending to employers. Facts may be incomplete or inaccurate.';

export type AiResumeProvenance = {
  /** Always true for these endpoints — clients must show an AI badge. */
  aiGenerated: true;
  aiLabel: typeof AI_RESUME_LABEL;
  aiDisclaimer: typeof AI_RESUME_DISCLAIMER;
  provider: 'openai';
  model: string;
  generatedAt: string;
  purpose: 'resume_builder' | 'job_tailoring';
};

export type AiResumeContent = {
  headline: string;
  summary: string;
  skills: string[];
  experience: Array<{
    title: string;
    company: string;
    bullets: string[];
  }>;
  education: Array<{
    degree: string;
    institution: string;
    highlight: string;
  }>;
  certifications: string[];
  plainText: string;
};

type AiResumePayload = AiResumeProvenance & {
  job: { id: string; title: string; companyName: string } | null;
  resume: AiResumeContent;
  tips: string[];
  /** Explicit UI hint for frontends. */
  uiHint: {
    showAiBadge: true;
    badgeText: 'AI-generated';
    bannerText: string;
  };
};

function asStringArray(value: unknown, max = 30): string[] {
  if (!Array.isArray(value)) return [];
  return value
    .map((item) => (typeof item === 'string' ? item.trim() : ''))
    .filter(Boolean)
    .slice(0, max);
}

function parseAiResumeJson(raw: string): {
  resume: AiResumeContent;
  tips: string[];
} {
  let parsed: Record<string, unknown>;
  try {
    parsed = JSON.parse(raw) as Record<string, unknown>;
  } catch {
    throw new AppError('AI returned invalid JSON', HTTP_STATUS.SERVICE_UNAVAILABLE);
  }

  const resumeRaw = (parsed.resume ?? parsed) as Record<string, unknown>;
  const experienceRaw = Array.isArray(resumeRaw.experience) ? resumeRaw.experience : [];
  const educationRaw = Array.isArray(resumeRaw.education) ? resumeRaw.education : [];

  const experience = experienceRaw.slice(0, 8).map((item) => {
    const row = (item ?? {}) as Record<string, unknown>;
    return {
      title: typeof row.title === 'string' ? row.title.trim() : '',
      company: typeof row.company === 'string' ? row.company.trim() : '',
      bullets: asStringArray(row.bullets, 8),
    };
  });

  const education = educationRaw.slice(0, 6).map((item) => {
    const row = (item ?? {}) as Record<string, unknown>;
    return {
      degree: typeof row.degree === 'string' ? row.degree.trim() : '',
      institution: typeof row.institution === 'string' ? row.institution.trim() : '',
      highlight: typeof row.highlight === 'string' ? row.highlight.trim() : '',
    };
  });

  const headline = typeof resumeRaw.headline === 'string' ? resumeRaw.headline.trim() : '';
  const summary = typeof resumeRaw.summary === 'string' ? resumeRaw.summary.trim() : '';
  const skills = asStringArray(resumeRaw.skills, 40);
  const certifications = asStringArray(resumeRaw.certifications, 20);
  let plainText = typeof resumeRaw.plainText === 'string' ? resumeRaw.plainText.trim() : '';

  if (!plainText) {
    plainText = [
      headline,
      summary,
      skills.length ? `Skills: ${skills.join(', ')}` : '',
      ...experience.map(
        (exp) =>
          `${exp.title}${exp.company ? ` @ ${exp.company}` : ''}\n${exp.bullets.map((b) => `• ${b}`).join('\n')}`,
      ),
      ...education.map(
        (edu) =>
          `${edu.degree}${edu.institution ? ` — ${edu.institution}` : ''}${edu.highlight ? `\n${edu.highlight}` : ''}`,
      ),
      certifications.length ? `Certifications: ${certifications.join(', ')}` : '',
    ]
      .filter(Boolean)
      .join('\n\n');
  }

  return {
    resume: {
      headline,
      summary,
      skills,
      experience,
      education,
      certifications,
      plainText,
    },
    tips: asStringArray(parsed.tips, 10),
  };
}

function buildProvenance(
  purpose: AiResumeProvenance['purpose'],
  model: string,
): AiResumeProvenance {
  return {
    aiGenerated: true,
    aiLabel: AI_RESUME_LABEL,
    aiDisclaimer: AI_RESUME_DISCLAIMER,
    provider: 'openai',
    model,
    generatedAt: new Date().toISOString(),
    purpose,
  };
}

function wrapPayload(
  purpose: AiResumeProvenance['purpose'],
  model: string,
  resume: AiResumeContent,
  tips: string[],
  job: AiResumePayload['job'],
): AiResumePayload {
  const provenance = buildProvenance(purpose, model);
  const bannerText =
    purpose === 'job_tailoring'
      ? 'AI-tailored for this job — review carefully before applying'
      : 'AI-generated resume draft — review carefully before using';

  return {
    ...provenance,
    job,
    resume,
    tips,
    uiHint: {
      showAiBadge: true,
      badgeText: 'AI-generated',
      bannerText,
    },
  };
}

async function loadCandidateContext(candidate: AuthenticatedCandidate) {
  const [user, candidateDoc] = await Promise.all([
    User.findById(candidate.userId).select('name email phone'),
    Candidate.findById(candidate.candidateId),
  ]);
  if (!user || !candidateDoc) {
    throw new AppError('Candidate not found', HTTP_STATUS.NOT_FOUND);
  }
  return { user, candidateDoc };
}

function profileSnapshot(
  user: { name?: string; email?: string; phone?: string },
  candidateDoc: InstanceType<typeof Candidate>,
) {
  return {
    name: user.name ?? '',
    email: user.email ?? '',
    phone: user.phone ?? '',
    headline: candidateDoc.headline ?? '',
    bio: candidateDoc.bio ?? '',
    currentJobTitle: candidateDoc.currentJobTitle ?? '',
    currentCompany: candidateDoc.currentCompany ?? '',
    currentLocation: candidateDoc.currentLocation ?? '',
    totalExperience: candidateDoc.totalExperience ?? 0,
    skills: candidateDoc.skills ?? [],
    preferredRoles: candidateDoc.preferredRoles ?? [],
    education: (candidateDoc.education ?? []).map((row) => ({
      degree: row.degree ?? '',
      institution: row.institution ?? '',
      fieldOfStudy: row.fieldOfStudy ?? '',
      startYear: row.startYear,
      endYear: row.endYear,
    })),
    workExperience: (candidateDoc.workExperience ?? []).map((row) => ({
      title: row.jobTitle ?? '',
      company: row.company ?? '',
      description: row.description ?? '',
      startDate: row.startDate,
      endDate: row.endDate,
      isCurrent: row.isCurrent,
    })),
    certifications: (candidateDoc.certifications ?? []).map((row) => ({
      name: row.name ?? '',
      issuer: row.issuer ?? '',
    })),
    languages: (candidateDoc.languages ?? []).map((row) => ({
      name: row.name ?? '',
      proficiency: row.proficiency ?? '',
    })),
  };
}

const SYSTEM_PROMPT = `You are a professional resume writer for the Indian job market (WorkIndia).
Return ONLY valid JSON with this shape:
{
  "resume": {
    "headline": "string",
    "summary": "string (2-4 sentences)",
    "skills": ["string"],
    "experience": [{ "title": "string", "company": "string", "bullets": ["string"] }],
    "education": [{ "degree": "string", "institution": "string", "highlight": "string" }],
    "certifications": ["string"],
    "plainText": "full plain-text resume"
  },
  "tips": ["short tip for the candidate"]
}
Rules:
- Do NOT invent employers, degrees, or certifications that are not in the profile.
- You may rephrase and strengthen wording; keep facts truthful to the profile.
- Prefer concise, impact-oriented bullets.
- Write in clear professional English.
- Never claim content is human-written; it is AI-assisted draft content.`;

export class AiResumeService {
  async build(
    candidate: AuthenticatedCandidate,
    input: AiResumeBuildInput,
  ): Promise<AiResumePayload> {
    const { user, candidateDoc } = await loadCandidateContext(candidate);
    const profile = profileSnapshot(user, candidateDoc);

    const userPrompt = [
      'Build a polished resume draft from this candidate profile.',
      `Tone: ${input.tone}.`,
      input.focusRoles.length
        ? `Emphasize these target roles when possible: ${input.focusRoles.join(', ')}.`
        : 'Emphasize the candidate headline / preferred roles when present.',
      'Profile JSON:',
      JSON.stringify(profile),
    ].join('\n');

    const { content, model } = await openAiService.chatJson([
      { role: 'system', content: SYSTEM_PROMPT },
      { role: 'user', content: userPrompt },
    ]);

    const { resume, tips } = parseAiResumeJson(content);
    return wrapPayload('resume_builder', model, resume, tips, null);
  }

  async tailor(
    candidate: AuthenticatedCandidate,
    input: AiResumeTailorInput,
  ): Promise<AiResumePayload> {
    const { user, candidateDoc } = await loadCandidateContext(candidate);
    const profile = profileSnapshot(user, candidateDoc);

    const job = await Job.findById(input.jobId)
      .select('title description responsibilities requirements skills companyId status')
      .lean();
    if (!job) {
      throw new AppError('Job not found', HTTP_STATUS.NOT_FOUND);
    }

    const company = job.companyId
      ? await Company.findById(job.companyId).select('name').lean()
      : null;
    const companyName = company?.name?.trim() || 'Company';

    const jobSnapshot = {
      id: String(job._id),
      title: job.title,
      companyName,
      description: (job.description ?? '').slice(0, 4000),
      responsibilities: (job.responsibilities ?? []).slice(0, 20),
      requirements: (job.requirements ?? []).slice(0, 20),
      skills: (job.skills ?? []).slice(0, 30),
    };

    const userPrompt = [
      'Tailor a resume draft for this specific job posting.',
      `Tone: ${input.tone}.`,
      'Highlight overlapping skills and relevant experience. Do not invent facts.',
      'Profile JSON:',
      JSON.stringify(profile),
      'Job JSON:',
      JSON.stringify(jobSnapshot),
    ].join('\n');

    const { content, model } = await openAiService.chatJson([
      { role: 'system', content: SYSTEM_PROMPT },
      { role: 'user', content: userPrompt },
    ]);

    const { resume, tips } = parseAiResumeJson(content);
    return wrapPayload('job_tailoring', model, resume, tips, {
      id: jobSnapshot.id,
      title: jobSnapshot.title,
      companyName,
    });
  }
}

export const aiResumeService = new AiResumeService();
