import mongoose from 'mongoose';
import { randomUUID } from 'crypto';
import { HTTP_STATUS } from '../constants';
import { Application } from '../models/Application';
import { Candidate } from '../models/Candidate';
import { Job } from '../models/Job';
import { User } from '../models/User';
import type { AuthenticatedEmployer } from '../types/auth.types';
import { AppError } from '../utils/AppError';
import {
  scoreJobMatch,
  type CandidateMatchSource,
  type JobMatchSource,
} from '../utils/matchScore';
import { openAiService } from './openai.service';
import { employerAiMatchingService } from './employerAiMatching.service';
import type {
  GenerateInterviewQuestionsInput,
  GenerateMessageInput,
  ImproveJdInput,
  SaveInterviewQuestionsInput,
  ScreenCandidatesInput,
  SuggestCandidatesInput,
  SuggestSkillsInput,
  SummarizeProfileInput,
} from '../validators/employerAiRecruitment.validator';

export const EMPLOYER_AI_RECRUIT_LABEL = 'AI-generated';
export const EMPLOYER_AI_RECRUIT_DISCLAIMER =
  'This content was generated by AI (ChatGPT). Review and edit before publishing, messaging candidates, or making hiring decisions.';

type AiProvenance = {
  aiGenerated: true;
  aiLabel: typeof EMPLOYER_AI_RECRUIT_LABEL;
  aiDisclaimer: typeof EMPLOYER_AI_RECRUIT_DISCLAIMER;
  provider: 'openai';
  model: string;
  generatedAt: string;
  uiHint: {
    showAiBadge: true;
    badgeText: 'AI-generated';
    bannerText: string;
  };
};

function provenance(model: string, bannerText: string): AiProvenance {
  return {
    aiGenerated: true,
    aiLabel: EMPLOYER_AI_RECRUIT_LABEL,
    aiDisclaimer: EMPLOYER_AI_RECRUIT_DISCLAIMER,
    provider: 'openai',
    model,
    generatedAt: new Date().toISOString(),
    uiHint: {
      showAiBadge: true,
      badgeText: 'AI-generated',
      bannerText,
    },
  };
}

function asString(value: unknown, max = 2000): string {
  return typeof value === 'string' ? value.trim().slice(0, max) : '';
}

function asStringArray(value: unknown, max = 40): string[] {
  if (!Array.isArray(value)) return [];
  return value
    .map((item) => (typeof item === 'string' ? item.trim() : ''))
    .filter(Boolean)
    .slice(0, max);
}

function parseJsonObject(raw: string): Record<string, unknown> {
  try {
    return JSON.parse(raw) as Record<string, unknown>;
  } catch {
    throw new AppError('AI returned invalid JSON', HTTP_STATUS.SERVICE_UNAVAILABLE);
  }
}

function jobToMatchSource(job: {
  title?: string;
  skills?: string[] | null;
  requirements?: string[] | null;
  experienceMin?: number | null;
  experienceMax?: number | null;
  salaryMin?: number | null;
  salaryMax?: number | null;
  workMode?: string | null;
  location?: {
    displayName?: string;
    city?: string;
    address?: string;
    latitude?: number | null;
    longitude?: number | null;
  } | null;
}): JobMatchSource {
  const location = job.location;
  return {
    title: job.title,
    skills: job.skills,
    requirements: job.requirements,
    experienceMin: job.experienceMin,
    experienceMax: job.experienceMax,
    salaryMin: job.salaryMin,
    salaryMax: job.salaryMax,
    workMode: job.workMode,
    locationText: [location?.address, location?.city, location?.displayName]
      .filter(Boolean)
      .join(' '),
    latitude: typeof location?.latitude === 'number' ? location.latitude : null,
    longitude: typeof location?.longitude === 'number' ? location.longitude : null,
  };
}

function candidateToMatchSource(candidate: {
  headline?: string | null;
  currentJobTitle?: string | null;
  skills?: string[] | null;
  totalExperience?: number | null;
  expectedSalary?: number | null;
  currentLocation?: string | null;
  latitude?: number | null;
  longitude?: number | null;
  openToWork?: boolean | null;
  availableFrom?: Date | null;
  noticePeriod?: number | null;
}): CandidateMatchSource {
  return {
    headline: candidate.headline,
    currentJobTitle: candidate.currentJobTitle,
    skills: candidate.skills,
    totalExperience: candidate.totalExperience,
    expectedSalary: candidate.expectedSalary,
    currentLocation: candidate.currentLocation,
    latitude: candidate.latitude,
    longitude: candidate.longitude,
    openToWork: candidate.openToWork,
    availableFrom: candidate.availableFrom,
    noticePeriod: candidate.noticePeriod,
  };
}

function profileSnapshot(candidate: InstanceType<typeof Candidate>, name: string) {
  return {
    name,
    headline: candidate.headline ?? '',
    currentJobTitle: candidate.currentJobTitle ?? '',
    currentCompany: candidate.currentCompany ?? '',
    totalExperience: candidate.totalExperience ?? 0,
    skills: (candidate.skills ?? []).slice(0, 40),
    education: (candidate.education ?? []).slice(0, 4).map((edu) => ({
      degree: edu.degree ?? '',
      institution: edu.institution ?? '',
    })),
    experience: (candidate.workExperience ?? []).slice(0, 5).map((exp) => ({
      title: exp.jobTitle ?? '',
      company: exp.company ?? '',
      description: (exp.description ?? '').slice(0, 400),
    })),
    expectedSalary: candidate.expectedSalary ?? null,
    noticePeriod: candidate.noticePeriod ?? null,
    currentLocation: candidate.currentLocation ?? '',
    bio: (candidate.bio ?? '').slice(0, 800),
  };
}

/**
 * Employer AI Recruitment Assistant + AI Interview (sheet 293–303).
 * All ChatGPT outputs are labelled AI-generated for client badges.
 */
export class EmployerAiRecruitmentService {
  private async ownedJob(employer: AuthenticatedEmployer, jobId: string) {
    if (!mongoose.Types.ObjectId.isValid(jobId)) {
      throw new AppError('Job not found', HTTP_STATUS.NOT_FOUND);
    }
    const job = await Job.findOne({
      _id: jobId,
      employerId: employer.employerId,
      companyId: employer.companyId,
      deletedAt: null,
    });
    if (!job) throw new AppError('Job not found', HTTP_STATUS.NOT_FOUND);
    return job;
  }

  private async loadCandidateForEmployer(
    employer: AuthenticatedEmployer,
    opts: { candidateId?: string; applicationId?: string; jobId?: string },
  ) {
    let candidateId = opts.candidateId;
    let application: InstanceType<typeof Application> | null = null;

    if (opts.applicationId) {
      if (!mongoose.Types.ObjectId.isValid(opts.applicationId)) {
        throw new AppError('Application not found', HTTP_STATUS.NOT_FOUND);
      }
      application = await Application.findOne({
        _id: opts.applicationId,
        employerId: employer.employerId,
        companyId: employer.companyId,
      });
      if (!application) throw new AppError('Application not found', HTTP_STATUS.NOT_FOUND);
      candidateId = application.candidateId.toString();
    }

    if (!candidateId || !mongoose.Types.ObjectId.isValid(candidateId)) {
      throw new AppError('Candidate not found', HTTP_STATUS.NOT_FOUND);
    }

    const candidate = await Candidate.findById(candidateId);
    if (!candidate) throw new AppError('Candidate not found', HTTP_STATUS.NOT_FOUND);

    const user = await User.findById(candidate.userId).select('name');
    const name = user?.name?.trim() || 'Candidate';

    let job: InstanceType<typeof Job> | null = null;
    const jobId = opts.jobId || application?.jobId?.toString();
    if (jobId) {
      job = await this.ownedJob(employer, jobId).catch(() => null);
    }

    return { candidate, name, application, job };
  }

  /** 293 — Create / improve JD. */
  async improveJd(_employer: AuthenticatedEmployer, input: ImproveJdInput) {
    const { content, model } = await openAiService.chatJson(
      [
        {
          role: 'system',
          content:
            'You improve job descriptions for Indian hiring platforms. Return JSON only: { "title": string, "description": string, "responsibilities": string[], "requirements": string[], "skills": string[], "tips": string[] }. Keep language clear, inclusive, and factual. Do not invent salary or company claims.',
        },
        {
          role: 'user',
          content: JSON.stringify({
            tone: input.tone,
            draft: {
              title: input.title,
              description: input.description,
              responsibilities: input.responsibilities,
              requirements: input.requirements,
              skills: input.skills,
              experienceMin: input.experienceMin,
              experienceMax: input.experienceMax,
              workMode: input.workMode,
              employmentType: input.employmentType,
            },
          }),
        },
      ],
      { temperature: 0.45 },
    );

    const parsed = parseJsonObject(content);
    return {
      ...provenance(model, 'AI-improved job description — review before publishing'),
      purpose: 'improve_jd' as const,
      draft: {
        title: asString(parsed.title, 200) || input.title,
        description: asString(parsed.description, 20000) || input.description,
        responsibilities: asStringArray(parsed.responsibilities, 30),
        requirements: asStringArray(parsed.requirements, 30),
        skills: asStringArray(parsed.skills, 40),
      },
      tips: asStringArray(parsed.tips, 8),
    };
  }

  /** 294 — Suggest skills for a role. */
  async suggestSkills(_employer: AuthenticatedEmployer, input: SuggestSkillsInput) {
    const { content, model } = await openAiService.chatJson(
      [
        {
          role: 'system',
          content:
            'Suggest practical job skills for hiring in India. Return JSON: { "skills": string[], "mustHave": string[], "niceToHave": string[] }. Prefer concise skill names. Avoid duplicates of existingSkills.',
        },
        {
          role: 'user',
          content: JSON.stringify({
            title: input.title,
            description: input.description,
            existingSkills: input.existingSkills,
            limit: input.limit,
          }),
        },
      ],
      { temperature: 0.35 },
    );

    const parsed = parseJsonObject(content);
    const existing = new Set(input.existingSkills.map((s) => s.toLowerCase()));
    const filterNew = (arr: string[]) =>
      arr.filter((s) => !existing.has(s.toLowerCase())).slice(0, input.limit);

    return {
      ...provenance(model, 'AI-suggested skills — review before adding to the JD'),
      purpose: 'suggest_skills' as const,
      skills: filterNew(asStringArray(parsed.skills, input.limit)),
      mustHave: filterNew(asStringArray(parsed.mustHave, 12)),
      niceToHave: filterNew(asStringArray(parsed.niceToHave, 12)),
    };
  }

  /** 295 — Screen applicants for a job with AI notes. */
  async screenCandidates(employer: AuthenticatedEmployer, input: ScreenCandidatesInput) {
    const job = await this.ownedJob(employer, input.jobId);
    const filter: Record<string, unknown> = {
      jobId: job._id,
      employerId: employer.employerId,
      companyId: employer.companyId,
      status: { $nin: ['withdrawn'] },
    };
    if (input.applicationIds.length > 0) {
      filter._id = { $in: input.applicationIds };
    }

    const applications = await Application.find(filter)
      .sort({ appliedAt: -1 })
      .limit(input.limit);

    if (applications.length === 0) {
      return {
        ...provenance(openAiService.getModel(), 'No applicants to screen yet'),
        purpose: 'screen_candidates' as const,
        job: { id: job._id.toString(), title: job.title },
        results: [] as unknown[],
      };
    }

    const candidates = await Candidate.find({
      _id: { $in: applications.map((a) => a.candidateId) },
    });
    const users = await User.find({
      _id: { $in: candidates.map((c) => c.userId) },
    }).select('name');
    const candidateMap = new Map(candidates.map((c) => [c._id.toString(), c]));
    const userMap = new Map(users.map((u) => [u._id.toString(), u]));

    const jobSource = jobToMatchSource(job);
    const rows = applications.map((app) => {
      const candidate = candidateMap.get(app.candidateId.toString());
      const match = candidate
        ? scoreJobMatch(jobSource, candidateToMatchSource(candidate))
        : null;
      const name = candidate
        ? userMap.get(candidate.userId.toString())?.name?.trim() || 'Candidate'
        : 'Candidate';
      return {
        applicationId: app._id.toString(),
        candidateId: app.candidateId.toString(),
        name,
        status: app.status,
        matchPercentage: match?.overall ?? 0,
        matchingSkills: match?.matchingSkills ?? [],
        missingSkills: match?.missingSkills ?? [],
        snapshot: candidate
          ? {
              headline: candidate.headline ?? '',
              experienceYears: candidate.totalExperience ?? 0,
              skills: (candidate.skills ?? []).slice(0, 20),
              expectedSalary: candidate.expectedSalary ?? null,
            }
          : null,
      };
    });

    const { content, model } = await openAiService.chatJson(
      [
        {
          role: 'system',
          content:
            'You are an AI recruiting screener. For each applicant return JSON: { "screens": [ { "applicationId": string, "recommendation": "advance"|"maybe"|"reject", "score": number 0-100, "summary": string, "strengths": string[], "concerns": string[] } ] }. Be fair and concise. Do not invent facts not in the data.',
        },
        {
          role: 'user',
          content: JSON.stringify({
            job: {
              title: job.title,
              description: (job.description ?? '').slice(0, 2500),
              skills: job.skills ?? [],
              experienceMin: job.experienceMin,
              experienceMax: job.experienceMax,
            },
            applicants: rows,
          }),
        },
      ],
      { temperature: 0.3 },
    );

    const parsed = parseJsonObject(content);
    const screensRaw = Array.isArray(parsed.screens) ? parsed.screens : [];
    const screenMap = new Map<string, Record<string, unknown>>();
    for (const item of screensRaw) {
      const row = (item ?? {}) as Record<string, unknown>;
      const id = asString(row.applicationId, 64);
      if (id) screenMap.set(id, row);
    }

    const results = rows.map((row) => {
      const ai = screenMap.get(row.applicationId) ?? {};
      const recommendationRaw = asString(ai.recommendation, 20).toLowerCase();
      const recommendation =
        recommendationRaw === 'advance' || recommendationRaw === 'reject'
          ? recommendationRaw
          : 'maybe';
      return {
        ...row,
        recommendation,
        aiScore:
          typeof ai.score === 'number' && Number.isFinite(ai.score)
            ? Math.max(0, Math.min(100, Math.round(ai.score)))
            : row.matchPercentage,
        summary: asString(ai.summary, 600),
        strengths: asStringArray(ai.strengths, 6),
        concerns: asStringArray(ai.concerns, 6),
        aiGenerated: true as const,
        aiLabel: EMPLOYER_AI_RECRUIT_LABEL,
      };
    });

    results.sort((a, b) => b.aiScore - a.aiScore);

    return {
      ...provenance(model, 'AI screening notes — review before advancing or rejecting'),
      purpose: 'screen_candidates' as const,
      job: { id: job._id.toString(), title: job.title },
      results,
    };
  }

  /** 296 — Summarize a candidate profile. */
  async summarizeProfile(employer: AuthenticatedEmployer, input: SummarizeProfileInput) {
    const { candidate, name, job } = await this.loadCandidateForEmployer(employer, input);
    const snapshot = profileSnapshot(candidate, name);

    const { content, model } = await openAiService.chatJson(
      [
        {
          role: 'system',
          content:
            'Summarize candidate profiles for recruiters. Return JSON: { "headline": string, "summary": string, "highlights": string[], "risks": string[], "fitNotes": string }. Keep factual; do not invent employers or degrees.',
        },
        {
          role: 'user',
          content: JSON.stringify({
            candidate: snapshot,
            job: job
              ? {
                  title: job.title,
                  skills: job.skills ?? [],
                  description: (job.description ?? '').slice(0, 1500),
                }
              : null,
          }),
        },
      ],
      { temperature: 0.35 },
    );

    const parsed = parseJsonObject(content);
    return {
      ...provenance(model, 'AI profile summary — verify against the full profile'),
      purpose: 'summarize_profile' as const,
      candidate: {
        id: candidate._id.toString(),
        name,
      },
      job: job ? { id: job._id.toString(), title: job.title } : null,
      headline: asString(parsed.headline, 200),
      summary: asString(parsed.summary, 2000),
      highlights: asStringArray(parsed.highlights, 8),
      risks: asStringArray(parsed.risks, 6),
      fitNotes: asString(parsed.fitNotes, 1000),
    };
  }

  /** 297 — Suggest / rank candidates for a JD (AI insights on). */
  async suggestCandidates(employer: AuthenticatedEmployer, input: SuggestCandidatesInput) {
    const matches = await employerAiMatchingService.listMatchesForJob(
      employer,
      input.jobId,
      {
        limit: input.limit,
        minScore: input.minScore,
        withAiInsights: true,
      },
      'aiCandidateSuggestEnabled',
    );

    return {
      ...matches,
      ...provenance(
        openAiService.getModel(),
        'AI-suggested candidates for this JD — review match scores before contacting',
      ),
      purpose: 'suggest_candidates' as const,
    };
  }

  /** 298 + 301–303 — Generate / regenerate interview questions. */
  async generateInterviewQuestions(
    employer: AuthenticatedEmployer,
    input: GenerateInterviewQuestionsInput,
  ) {
    let role = input.role?.trim() || '';
    let skills = input.skills ?? [];
    let experienceYears = input.experienceYears;
    let jobId: string | undefined;

    if (input.jobId) {
      const job = await this.ownedJob(employer, input.jobId);
      jobId = job._id.toString();
      if (!role) role = job.title;
      if (skills.length === 0) skills = (job.skills ?? []).slice(0, 30);
      if (experienceYears === undefined) {
        experienceYears = job.experienceMin ?? 0;
      }
    }

    if (!role) {
      throw new AppError('Role is required', HTTP_STATUS.BAD_REQUEST);
    }

    const { content, model } = await openAiService.chatJson(
      [
        {
          role: 'system',
          content:
            'Generate interview questions for Indian employers. Return JSON: { "questions": [ { "text": string, "category": "technical"|"behavioral"|"situational"|"culture", "difficulty": "easy"|"medium"|"hard" } ], "tips": string[] }. Questions must be relevant to role, experience, and skills. When regenerating, produce a fresh set different from previousQuestions.',
        },
        {
          role: 'user',
          content: JSON.stringify({
            role,
            experienceYears: experienceYears ?? null,
            skills,
            count: input.count,
            difficulty: input.difficulty,
            regenerate: input.regenerate,
            previousQuestions: input.previousQuestions,
          }),
        },
      ],
      { temperature: input.regenerate ? 0.7 : 0.4 },
    );

    const parsed = parseJsonObject(content);
    const rawQs = Array.isArray(parsed.questions) ? parsed.questions : [];
    const questions = rawQs.slice(0, input.count).map((item, index) => {
      const row = (item ?? {}) as Record<string, unknown>;
      const difficultyRaw = asString(row.difficulty, 20).toLowerCase();
      const difficulty =
        difficultyRaw === 'easy' || difficultyRaw === 'hard' ? difficultyRaw : 'medium';
      return {
        id: `aiq_${randomUUID().slice(0, 8)}_${index}`,
        text: asString(row.text, 500),
        category: asString(row.category, 80) || 'general',
        difficulty: difficulty as 'easy' | 'medium' | 'hard',
      };
    }).filter((q) => q.text.length >= 3);

    if (questions.length === 0) {
      throw new AppError('AI returned no interview questions', HTTP_STATUS.SERVICE_UNAVAILABLE);
    }

    return {
      ...provenance(
        model,
        input.regenerate
          ? 'AI-regenerated interview questions — review before saving'
          : 'AI interview questions — review before saving or using',
      ),
      purpose: 'interview_questions' as const,
      jobId: jobId ?? null,
      role,
      experienceYears: experienceYears ?? null,
      skills,
      questions,
      tips: asStringArray(parsed.tips, 6),
    };
  }

  /** 303 — Persist AI interview kit on an owned job. */
  async saveInterviewQuestions(
    employer: AuthenticatedEmployer,
    input: SaveInterviewQuestionsInput,
  ) {
    const job = await this.ownedJob(employer, input.jobId);
    const questions = input.questions.map((q, index) => ({
      id: q.id?.trim() || `aiq_${randomUUID().slice(0, 8)}_${index}`,
      text: q.text.trim(),
      category: (q.category || 'general').trim().slice(0, 80),
      difficulty: q.difficulty || 'medium',
    }));

    job.set('aiInterviewKit', {
      role: input.role.trim(),
      experienceYears: input.experienceYears ?? null,
      skills: input.skills ?? [],
      questions,
      savedAt: new Date(),
      model: openAiService.getModel(),
      aiGenerated: true,
    });
    await job.save();

    return {
      ...provenance(openAiService.getModel(), 'Saved AI interview questions on this job'),
      purpose: 'save_interview_questions' as const,
      jobId: job._id.toString(),
      kit: {
        role: input.role.trim(),
        experienceYears: input.experienceYears ?? null,
        skills: input.skills ?? [],
        questions,
        savedAt: new Date().toISOString(),
        aiGenerated: true as const,
        aiLabel: EMPLOYER_AI_RECRUIT_LABEL,
      },
    };
  }

  async getSavedInterviewQuestions(employer: AuthenticatedEmployer, jobId: string) {
    const job = await this.ownedJob(employer, jobId);
    const kit = (job.get('aiInterviewKit') ?? null) as {
      role?: string;
      experienceYears?: number | null;
      skills?: string[];
      questions?: Array<{
        id?: string;
        text?: string;
        category?: string;
        difficulty?: string;
      }>;
      savedAt?: Date;
      model?: string;
      aiGenerated?: boolean;
    } | null;

    if (!kit || !Array.isArray(kit.questions) || kit.questions.length === 0) {
      return {
        jobId: job._id.toString(),
        kit: null,
        aiGenerated: false as const,
      };
    }

    return {
      ...provenance(
        kit.model || openAiService.getModel(),
        'Saved AI interview questions for this job',
      ),
      purpose: 'saved_interview_questions' as const,
      jobId: job._id.toString(),
      kit: {
        role: kit.role ?? job.title,
        experienceYears: kit.experienceYears ?? null,
        skills: kit.skills ?? [],
        questions: kit.questions.map((q, index) => ({
          id: q.id || `saved_${index}`,
          text: q.text ?? '',
          category: q.category ?? 'general',
          difficulty: (q.difficulty as 'easy' | 'medium' | 'hard') || 'medium',
        })),
        savedAt: kit.savedAt ? new Date(kit.savedAt).toISOString() : null,
        aiGenerated: true as const,
        aiLabel: EMPLOYER_AI_RECRUIT_LABEL,
      },
    };
  }

  /** 299 — Selection / offer-style message. */
  async generateSelectionMessage(employer: AuthenticatedEmployer, input: GenerateMessageInput) {
    return this.generateMessage(employer, input, 'selection');
  }

  /** 300 — Rejection message. */
  async generateRejectionMessage(employer: AuthenticatedEmployer, input: GenerateMessageInput) {
    return this.generateMessage(employer, input, 'rejection');
  }

  private async generateMessage(
    employer: AuthenticatedEmployer,
    input: GenerateMessageInput,
    kind: 'selection' | 'rejection',
  ) {
    let candidateName = input.candidateName?.trim() || '';
    let jobTitle = input.jobTitle?.trim() || '';

    if (input.applicationId || input.candidateId) {
      const loaded = await this.loadCandidateForEmployer(employer, {
        applicationId: input.applicationId,
        candidateId: input.candidateId,
        jobId: input.jobId,
      });
      if (!candidateName) candidateName = loaded.name;
      if (!jobTitle && loaded.job) jobTitle = loaded.job.title;
    } else if (input.jobId) {
      const job = await this.ownedJob(employer, input.jobId);
      if (!jobTitle) jobTitle = job.title;
    }

    if (!candidateName) candidateName = 'Candidate';
    if (!jobTitle) jobTitle = 'the role';

    const system =
      kind === 'selection'
        ? 'Write a short, warm selection / shortlist message an employer can send to a candidate in India. Return JSON: { "subject": string, "body": string, "variants": string[] }. Keep under 120 words. No salary promises unless in notes.'
        : 'Write a respectful rejection message an employer can send to a candidate in India. Return JSON: { "subject": string, "body": string, "variants": string[] }. Keep under 100 words. Be kind and professional; leave the door open when appropriate.';

    const { content, model } = await openAiService.chatJson(
      [
        { role: 'system', content: system },
        {
          role: 'user',
          content: JSON.stringify({
            tone: input.tone,
            candidateName,
            jobTitle,
            notes: input.notes,
          }),
        },
      ],
      { temperature: 0.5 },
    );

    const parsed = parseJsonObject(content);
    return {
      ...provenance(
        model,
        kind === 'selection'
          ? 'AI selection message — edit before sending'
          : 'AI rejection message — edit before sending',
      ),
      purpose: kind === 'selection' ? ('selection_message' as const) : ('rejection_message' as const),
      candidateName,
      jobTitle,
      subject: asString(parsed.subject, 200),
      body: asString(parsed.body, 4000),
      variants: asStringArray(parsed.variants, 3),
    };
  }
}

export const employerAiRecruitmentService = new EmployerAiRecruitmentService();
